src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="The field email is required")
     * @Assert\Email(message="Please enter a valid email address")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="The field password is required")
     * @Assert\Length(max=4096)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=45)
     * @Assert\NotBlank(message="The field name is required")
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=45)
     * @Assert\NotBlank(message="The field last name is required")
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vimeo_api_key;

    /**
     * @ORM\ManyToMany(targetEntity=Video::class, mappedBy="usersThatLike")
     * @ORM\JoinTable(name="likes")
     */
    private $likedVideos;

    /**
     * @ORM\ManyToMany(targetEntity=Video::class, mappedBy="usersThatDontLike")
     * @ORM\JoinTable(name="dislikes")
     */
    private $dislikedVideos;

    /**
     * @ORM\OneToOne(targetEntity=Subscription::class, cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $subscription;

    public function __construct()
    {
        $this->likedVideos = new ArrayCollection();
        $this->dislikedVideos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getVimeoApiKey(): ?string
    {
        return $this->vimeo_api_key;
    }

    public function setVimeoApiKey(?string $vimeo_api_key): self
    {
        $this->vimeo_api_key = $vimeo_api_key;

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getLikedVideos(): Collection
    {
        return $this->likedVideos;
    }

    public function addLikedVideo(Video $likedVideo): self
    {
        if (!$this->likedVideos->contains($likedVideo)) {
            $this->likedVideos[] = $likedVideo;
            $likedVideo->addUsersThatLike($this);
        }

        return $this;
    }

    public function removeLikedVideo(Video $likedVideo): self
    {
        if ($this->likedVideos->removeElement($likedVideo)) {
            $likedVideo->removeUsersThatLike($this);
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getDislikedVideos(): Collection
    {
        return $this->dislikedVideos;
    }

    public function addDislikedVideo(Video $dislikedVideo): self
    {
        if (!$this->dislikedVideos->contains($dislikedVideo)) {
            $this->dislikedVideos[] = $dislikedVideo;
            $dislikedVideo->addUsersThatDontLike($this);
        }

        return $this;
    }

    public function removeDislikedVideo(Video $dislikedVideo): self
    {
        if ($this->dislikedVideos->removeElement($dislikedVideo)) {
            $dislikedVideo->removeUsersThatDontLike($this);
        }

        return $this;
    }

    public function getSubscription(): ?Subscription
    {
        return $this->subscription;
    }

    public function setSubscription(?Subscription $subscription): self
    {
        $this->subscription = $subscription;

        return $this;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Comment;
use App\Entity\Video;
use App\Repository\VideoRepository;
use App\Utils\CategoryTreeFronPage;
use App\Utils\Interfaces\CacheInterface;
use App\Utils\VideoForNoValidSubscription;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class FrontController extends AbstractController
{
    /**
     * @Route("/", name="main_page")
     */
    public function index(Session $session)
    {
//        $session->set('test', 'hello world');
//        dump($session->get('test'));
        return $this->render('front/index.html.twig');
    }

    /**
     * @Route("/video-list/category/{categoryname},{id}", name="video_list")
     * @param $id
     * @param CategoryTreeFronPage $categories
     * @param CacheInterface $cache
     * @param Request $request
     * @param VideoForNoValidSubscription $videoNoMembers
     * @return \Symfony\Component\HttpFoundation\Response
     */
	public function videoList($id, CategoryTreeFronPage $categories, CacheInterface $cache,
                              Request $request, VideoForNoValidSubscription $videoNoMembers)
	{
	    $manager = $this->getDoctrine()->getManager();
        $page = $request->query->getInt('page' ,1);
        $perPage = $request->query->getInt('perPage', 5);
        $sort = $request->query->get('sortBy', 'asc');

        $cache = $cache->cache;
        $videoList = $cache->getItem('video_list'.$id.$page.$sort);
        $videoList->expiresAfter(60);
        if(!$videoList->isHit()){
            $ids = $categories->getChildIds($id);
            $videos = $manager->getRepository(Video::class)->findByChildIds($ids, $page, $perPage, $sort);

            $categories->getCategoryListAndParent($id);
            //	    dump($categories, $ids);
            $response = $this->render('front/video_list.html.twig', [
                'categories' => $categories,
                'videos' => $videos,
                'videoNoMembers' => $videoNoMembers->check()
            ]);

             $videoList->set($response);
             $cache->save($videoList);
        }

        return $videoList->get();
	}

    /**
     * @Route("/video-details/{video}", name="video_details")
     * @param VideoRepository $videoRepository
     * @param Video $video
     * @param VideoForNoValidSubscription $videoNoMembers
     * @return \Symfony\Component\HttpFoundation\Response
     */
	public function videoDetails(VideoRepository $videoRepository,
                                 Video $video, VideoForNoValidSubscription $videoNoMembers)
	{
        $video = $videoRepository->videoDetail($video);

		return $this->render('front/video_details.html.twig', [
		    'video' => $video,
            'videoNoMembers' => $videoNoMembers->check()
        ]);
	}

    /** @Route("/store-comment/{video}", name="store_comment", methods={"POST"})
     * @param Video $video
     */
	public function storeComment(Video $video, Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');
        $manager = $this->getDoctrine()->getManager();
        if(! $this->isCsrfTokenValid('store-comment', $request->request->get('token'))) {
            throw new \Exception('Csrf is invalid');
        }

        $comment = new Comment();
        $comment->setUser($this->getUser());
        $comment->setVideo($video);
        $comment->setContent($request->request->get('content'));
        $manager->persist($comment);
        $manager->flush();

        return $this->redirectToRoute('video_details', ['video' => $video->getId()]);
    }

    /**
     * @Route("/search-results", name="search_results", methods={"GET"})
     * @param Request $request
     * @param VideoForNoValidSubscription $videoNoMembers
     * @return \Symfony\Component\HttpFoundation\Response
     */
	public function searchResults(Request $request, VideoForNoValidSubscription $videoNoMembers)
	{
        $query = $request->query->get('query', null);
        $videos = null;

	    if(!empty($query)) {
            $manager = $this->getDoctrine()->getManager();
            $page = $request->query->getInt('page' ,1);
            $perPage = $request->query->getInt('perPage', 5);
            $sort = $request->query->get('sortBy', 'asc');

            $videos = $manager->getRepository(Video::class)->findByTitle($query, $page, $perPage, $sort);
        }

		return $this->render('front/search_results.html.twig', [
		    'videos' => $videos,
            'query' => $query,
            'videoNoMembers' => $videoNoMembers->check()
        ]);
	}

	public function mainCategories()
	{
		$mainCategories = $this->getDoctrine()
		                       ->getRepository(Category::class)
		                       ->findBy(['parent' => null], ['name' => 'ASC']);

		return $this->render('front/includes/_menu_links.html.twig', [
			'mainCategories' => $mainCategories
		]);
	}

    /**
     * @Route("delete-comment/{comment}", name="delete_comment")
     * @Security("user.getId() == comment.getUser().getId()")
     * @param Comment $comment
     * @param Request $request
     */
	public function deleteComment(Comment $comment, Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');

        $em = $this->getDoctrine()->getManager();
        $em->remove($comment);
        $em->flush();

        $this->addFlash('success', 'Comment has been deleted');
        return $this->redirect($request->headers->get('referer'));
    }

}

templates/front/index.html.twig
{% extends "base.html.twig" %}

{% block content %}

    <h1 class="text-info mb-5 mt-4">Where the best videos happens</h1>

    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://player.vimeo.com/video/137857207" allowfullscreen></iframe>
    </div>

{% endblock %}

templates/front/login.html.twig
{% extends 'base.html.twig' %}

{% block menu %}{% endblock %}
{% block footer_links %}{% endblock %}
{% block styles %}
<link rel="stylesheet" href="{{ asset('assets/css/login.css') }}">
{% endblock %}

{% block content %}
{% if error is not empty%}
    <div class="alert alert-danger">
        {{ error.messageKey|trans(error.messageData, 'security') }}
    </div>
{% endif %}
<form method="POST" action="{{ path('login') }}" class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus name="_email">
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="_password">
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" name="_remeber_me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2018 <a href="{{ path('main_page') }}">main page</a></p>
    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
</form>
{% endblock %}

templates/front/payment.html.twig
{% extends 'base.html.twig' %}

{% block content %}
<br>

<div class="row mt-5">
   {{ include('front/includes/_cart.html.twig') }}

    <div class="col-md-8 order-md-1">

        <h4 class="mb-3">Pay with PayPal <small>or get other <a href="{{ path('pricing') }}">plan</a></small></h4>
        <hr class="mb-4">
        <a href="{{ subscribe }}" class="btn btn-primary btn-lg btn-block" role="button">Continue to checkout</a>
    </div>
</div>

{% endblock %}

templates/front/pricing.html.twig
{% extends 'base.html.twig' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Pricing</h1>
    <p class="lead">Watch the best videos on the planet. Choose a plan that is right for you. Downgrade or upgrade at
        any time.
    </p>
</div>

<div class="container">
    <div class="card-deck mb-3 text-center">
        {%  for name in names %}
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ name | capitalize }}</h4>
            </div>
            {% if name == 'free' %}
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">${{ prices[name] }}<small class="text-muted">/ mo</small></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Access for one month</li>
                        <li>Help center access</li>
                    </ul>
                    <a role="button" href="{{ path('register', {'plan': name}) }}" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</a>
                </div>
            {% endif %}
            {% if name == 'pro' %}
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Unlimited access</li>
                        <li>HD available</li>
                        <li>No ads on videos</li>
                        <li>Help center access</li>
                    </ul>
                    <a role="button" href="{{ path('register', {'plan': name}) }}" class="btn btn-lg btn-block btn-primary">Get started</a>
                </div>
            {% endif %}
            {% if name == 'enterprise' %}
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Unlimited access</li>
                    <li>Ultra HD available</li>
                    <li>No ads on videos</li>
                    <li>Help center access</li>
                    <li>Unlimited live events</li>
                </ul>
                <a role="button" href="{{ path('register', {'plan': name}) }}" class="btn btn-lg btn-block btn-primary">Contact us</a>
            </div>
            {% endif %}
        </div>
        {% endfor %}

    </div>

</div>

{% endblock %}

templates/front/register.html.twig
{% extends 'base.html.twig' %}

{% block content %}

<div class="row mt-5">
    {{ include('front/includes/_cart.html.twig') }}

    <div class="col-md-8 order-md-1">
        <h4 class="mb-3">Register first (free)</h4>
            {{ form_start(form, {'attr': {'class':'needs-validation'}}) }}
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="user_name">First name</label>
                    {{ form_widget(form.name) }}
                    <div class="invalid-feedback">
                        {{ form_errors(form.name) }}
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="user_last_name">Last name</label>
                    {{ form_widget(form.last_name) }}
                    <div class="invalid-feedback">
                        {{ form_errors(form.last_name) }}
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <label for="user_email">Email</label>
                {{ form_widget(form.email) }}
                <div class="invalid-feedback">
                    {{ form_errors(form.email) }}
                </div>
            </div>

            <div class="mb-3">
                <label for="user_password_first">Password</label>
                {{ form_widget(form.password.first) }}
                <div class="invalid-feedback">
                    {{ form_errors(form.password.first) }}
                </div>
            </div>

            <div class="mb-3">
                <label for="user_password_second">Confirm Password</label>
                {{ form_widget(form.password.second) }}
                <div class="invalid-feedback">
                    {{ form_errors(form.password.second) }}
                </div>
            </div>

            <hr class="mb-4">
            <button type="submit" class="btn btn-primary btn-lg btn-block" role="button">Register</button>
       {{ form_end(form) }}

    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
	// Example starter JavaScript for disabling form submissions if there are invalid fields
	(function () {
		'use strict';

		window.addEventListener('load', function () {
			// Fetch all the forms we want to apply custom Bootstrap validation styles to
			var forms = document.getElementsByClassName('needs-validation');

			// Loop over them and prevent submission
			var validation = Array.prototype.filter.call(forms, function (form) {
				form.addEventListener('click', function (event) {
					if (form.checkValidity() === false) {
						event.preventDefault();
						event.stopPropagation();
					}
					form.classList.add('was-validated');
				}, false);
			});
		}, false);
	})();


	var password = document.getElementById("user_password_first"), confirm_password = document.getElementById("user_password_second");

	function validatePassword() {
		if (password.value != confirm_password.value) {
			confirm_password.setCustomValidity("Passwords Don't Match");
		} else {
			confirm_password.setCustomValidity('');
		}
	}
	password.addEventListener('onchange', validatePassword);
	confirm_password.onkeyup = validatePassword;
</script>
{% endblock %}

templates/front/search_results.html.twig
{% extends 'base.html.twig' %}

{% block styles %}
    {{ parent() }}
    {% if app.user %}
        <link rel="stylesheet" type="text/css" href="{{  asset('build/css/likes.css') }}">
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ parent() }}
    {% if app.user %}
        {{ encore_entry_script_tags('likes') }}
    {% endif %}
{% endblock %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        {% if videos is empty %}
        <h1 class="jumbotron-heading">No results were found</h1>
        {% else %}
        <h1 class="jumbotron-heading">Search results</h1>
            {{ include('front/includes/_sort.html.twig') }}
        {% endif %}
    </div>
</section>
<section>
    {% if videos is not empty %}
        {{ include('front/includes/_videos.html.twig', {'videos': videos}) }}
        <!-- pagination -->
        {{ knp_pagination_render(videos) }}
    {% endif %}
</section>
{% endblock %}

templates/front/video_details.html.twig
{% extends 'base.html.twig' %}

{% if videoNoMembers is not null %}
   {% set videoId = videoNoMembers %}
{% else %}
   {% set videoId = video.path %}
{% endif %}

{% block content %}
<br>

<h1>{{ video.getTitle() }}</h1>
<div align="center" class="embed-responsive embed-responsive-16by9">
    <iframe class="" src="{{ videoId }}" frameborder="0" allowfullscreen></iframe>
</div>

<hr>

<div class="row m-2">
    <div class="col-sm-12">
        <a id="video_comments"></a>
        {% for comment in video.comments %}
            <div class="media text-left">
                <img class="mr-3" src="{{ asset("assets/img/user.jpg") }}" alt="Generic placeholder image">
                <div class="media-body">
                    <h5 class="mt-0 mb-1"><b>{{ comment.user.name }} {{ comment.user.lastName }}</b>
                        <small class="text-muted">added a comment <small><b>{{ comment.getCreatedAt() | ago }}</b></small></small></h5>{{ comment.content }}
                    {% if app.user and comment.user.getId() == app.user.id %}
                        <a href="{{ path('delete_comment', {'comment': comment.id}) }}">Delete comment</a>
                    {% endif %}
                </div>
            </div>
            <hr>
        {% endfor %}
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <form method="POST" action="{{ path('store_comment', {'video': video.id}) }}#video_comments">
            <input type="hidden" name="token" value="{{ csrf_token('store-comment') }}"/>
            <div class="form-group">
                <label for="content">Add a comment</label>
                <textarea name="content" required class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary" value="Add">Add</button>

        </form>
    </div>
</div>

{% endblock %}

templates/front/video_list.html.twig
{% extends 'base.html.twig' %}

{% block styles %}
    {{ parent() }}
    {% if app.user %}
        <link rel="stylesheet" type="text/css" href="{{  asset('build/css/likes.css') }}">
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ parent() }}
    {% if app.user %}
        {{ encore_entry_script_tags('likes') }}
    {% endif %}
{% endblock %}

{% block content %}

    <main role="main">
        <section class="jumbotron text-center">
            <div class="container">

                <h1 class="jumbotron-heading">Category - {{ categories.currentCategoryName }}</h1>
                <div class="btn-group">
                    <div class="dropdown ml-2">
                        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            Subcategories
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <ul class="mr-5">
                                <li><a href="{{ path('video_list', {id: categories.mainParentId, categoryname: categories.mainParentName|slugify}) }}">{{ categories.mainParentName }}</a></li>
                                {{ categories.categoryList|raw }}
                            </ul>
                        </div>
                    </div>

                    <div class="form-row align-items-center ml-3">
                        {{ include('front/includes/_sort.html.twig') }}
                    </div>
                </div>
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">
                {{ include('front/includes/_videos.html.twig', {'videos': videos}) }}
            </div>
        </div>

        <!-- pagination -->
        {{ knp_pagination_render(videos) }}
    </main>
{% endblock %}